config/routes.rb
Rails.application.routes.draw do
  resources :legends
  resources :guns
  resources :attachments
  get 'items/guns'

  get 'items/attachments'

  get 'items/consumables'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match ':controller(/:action(/:id))', :via => :get
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
end

app/models/gun.rb
class Gun < ApplicationRecord
end

app/models/legend.rb
class Legend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:atmt_type, :atmt_name, :attaches_to, :color, :description)
    end
end

app/controllers/guns_controller.rb
class GunsController < ApplicationController
  before_action :set_gun, only: [:show, :edit, :update, :destroy]

  # GET /guns
  # GET /guns.json
  def index
    @guns = Gun.all
  end

  # GET /guns/1
  # GET /guns/1.json
  def show
  end

  # GET /guns/new
  def new
    @gun = Gun.new
  end

  # GET /guns/1/edit
  def edit
  end

  # POST /guns
  # POST /guns.json
  def create
    @gun = Gun.new(gun_params)

    respond_to do |format|
      if @gun.save
        format.html { redirect_to @gun, notice: 'Gun was successfully created.' }
        format.json { render :show, status: :created, location: @gun }
      else
        format.html { render :new }
        format.json { render json: @gun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guns/1
  # PATCH/PUT /guns/1.json
  def update
    respond_to do |format|
      if @gun.update(gun_params)
        format.html { redirect_to @gun, notice: 'Gun was successfully updated.' }
        format.json { render :show, status: :ok, location: @gun }
      else
        format.html { render :edit }
        format.json { render json: @gun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guns/1
  # DELETE /guns/1.json
  def destroy
    @gun.destroy
    respond_to do |format|
      format.html { redirect_to guns_url, notice: 'Gun was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gun
      @gun = Gun.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gun_params
      params.require(:gun).permit(:gun_name, :gun_type, :ammo_type, :gun_description, :gun_body, :gun_headshot, :mag_size)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	if(params.has_key?(:id))
  		@gun_id = params['id']
  	end
  end

  def guns
    @guns = Gun.all
  end
  
  def gun_stats
    @gun = Gun.find(params[:id])
  end

  def attachments
    @attachments = Attachment.all
  end

  def attachment_stats
    @attachment = Attachment.find(params[:id])
  end

  def legends
    @legends = Legend.all
  end

  def legend_stats
    @legend = Legend.find(params[:id])
  end

  def consumables
  end
end

app/controllers/legends_controller.rb
class LegendsController < ApplicationController
  before_action :set_legend, only: [:show, :edit, :update, :destroy]

  # GET /legends
  # GET /legends.json
  def index
    @legends = Legend.all
  end

  # GET /legends/1
  # GET /legends/1.json
  def show
  end

  # GET /legends/new
  def new
    @legend = Legend.new
  end

  # GET /legends/1/edit
  def edit
  end

  # POST /legends
  # POST /legends.json
  def create
    @legend = Legend.new(legend_params)

    respond_to do |format|
      if @legend.save
        format.html { redirect_to @legend, notice: 'Legend was successfully created.' }
        format.json { render :show, status: :created, location: @legend }
      else
        format.html { render :new }
        format.json { render json: @legend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legends/1
  # PATCH/PUT /legends/1.json
  def update
    respond_to do |format|
      if @legend.update(legend_params)
        format.html { redirect_to @legend, notice: 'Legend was successfully updated.' }
        format.json { render :show, status: :ok, location: @legend }
      else
        format.html { render :edit }
        format.json { render json: @legend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legends/1
  # DELETE /legends/1.json
  def destroy
    @legend.destroy
    respond_to do |format|
      format.html { redirect_to legends_url, notice: 'Legend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legend
      @legend = Legend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legend_params
      params.require(:legend).permit(:legend_name, :legend_desc, :legend_passive_name, :legend_passive_desc, :legend_ability_name, :legend_ability_desc, :legend_ult_name, :legend_ult_desc)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	def index
		require 'net/http'
		require 'uri'
		require 'httparty'
		require 'json'

		url = "https://public-api.tracker.gg/apex/v1/standard/profile/5/"
		url += params[:user]

		response = HTTParty.get(url,
			headers: {
				'TRN-Api-Key' => "0534a048-8000-4b48-a22f-71771ad0fc66"
			}, 
			:verify => false
		)

		@name = params[:user]
		@main_legend = response['data']['children'][0]['metadata']['legend_name']
		@level = response['data']['stats'][0]['displayValue']
		@bgimage = response['data']['children'][0]['metadata']['bgimage']
		@kills = response['data']['children'][0]['stats'][0]['displayValue']

		#puts params[:user]
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/guns_helper.rb
module GunsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/legends_helper.rb
module LegendsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attachments/_form.html.erb
<%= form_with(model: attachment, local: true) do |form| %>
  <% if attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :atmt_type %>
    <%= form.select :atmt_type, ['Hop Up', 'Optic', 'Magazine', 'Barrel', 'Stock'] %>
  </div>

  <div class="field">
    <%= form.label :atmt_name %>
    <%= form.text_field :atmt_name, id: :attachment_atmt_name %>
  </div>

  <div class="field">
    <%= form.label :attaches_to %>
    <%= form.text_field :attaches_to, id: :attachment_attaches_to %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :attachment_color %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :attachment_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Atmt type</th>
      <th>Atmt name</th>
      <th>Attaches to</th>
      <th>Color</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.atmt_type %></td>
        <td><%= attachment.atmt_name %></td>
        <td><%= attachment.attaches_to %></td>
        <td><%= attachment.color %></td>
        <td><%= attachment.description %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Atmt type:</strong>
  <%= @attachment.atmt_type %>
</p>

<p>
  <strong>Atmt name:</strong>
  <%= @attachment.atmt_name %>
</p>

<p>
  <strong>Attaches to:</strong>
  <%= @attachment.attaches_to %>
</p>

<p>
  <strong>Color:</strong>
  <%= @attachment.color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @attachment.description %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>

app/views/guns/_form.html.erb
<%= form_with(model: gun, local: true) do |form| %>
  <% if gun.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gun.errors.count, "error") %> prohibited this gun from being saved:</h2>

      <ul>
      <% gun.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :gun_name %>
    <%= form.text_field :gun_name, id: :gun_gun_name %>
  </div>

  <div class="field">
    <%= form.label :gun_type %>
    <%= form.select :gun_type, ['Pistol', 'Sub Machine Gun', 'Assault Rifle', 'Light Machine Gun', 'Sniper Rifle', 'Shotgun']  %>
  </div>

  <div class="field">
    <%= form.label :ammo_type %>
    <%= form.select :ammo_type, ['Light', 'Heavy', 'Shells', 'Energy', 'Special'] %>
  </div>

  <div class="field">
    <%= form.label :gun_description %>
    <%= form.text_field :gun_description, id: :gun_gun_description %>
  </div>

  <div class="field">
    <%= form.label :gun_body %>
    <%= form.number_field :gun_body, id: :gun_gun_body %>
  </div>

  <div class="field">
    <%= form.label :gun_headshot %>
    <%= form.number_field :gun_headshot, id: :gun_gun_headshot %>
  </div>

  <div class="field">
    <%= form.label :mag_size %>
    <%= form.number_field :mag_size, id: :gun_mag_size %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guns/edit.html.erb
<h1>Editing Gun</h1>

<%= render 'form', gun: @gun %>

<%= link_to 'Show', @gun %> |
<%= link_to 'Back', guns_path %>

app/views/guns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guns</h1>

<table>
  <thead>
    <tr>
      <th>Gun name</th>
      <th>Gun type</th>
      <th>Ammo type</th>
      <th>Gun description</th>
      <th>Gun body</th>
      <th>Gun headshot</th>
      <th>Mag size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guns.each do |gun| %>
      <tr>
        <td><%= gun.gun_name %></td>
        <td><%= gun.gun_type %></td>
        <td><%= gun.ammo_type %></td>
        <td><%= gun.gun_description %></td>
        <td><%= gun.gun_body %></td>
        <td><%= gun.gun_headshot %></td>
        <td><%= gun.mag_size %></td>
        <td><%= link_to 'Show', gun %></td>
        <td><%= link_to 'Edit', edit_gun_path(gun) %></td>
        <td><%= link_to 'Destroy', gun, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gun', new_gun_path %>

app/views/guns/new.html.erb
<h1>New Gun</h1>

<%= render 'form', gun: @gun %>

<%= link_to 'Back', guns_path %>

app/views/guns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gun name:</strong>
  <%= @gun.gun_name %>
</p>

<p>
  <strong>Gun type:</strong>
  <%= @gun.gun_type %>
</p>

<p>
  <strong>Ammo type:</strong>
  <%= @gun.ammo_type %>
</p>

<p>
  <strong>Gun description:</strong>
  <%= @gun.gun_description %>
</p>

<p>
  <strong>Gun body:</strong>
  <%= @gun.gun_body %>
</p>

<p>
  <strong>Gun headshot:</strong>
  <%= @gun.gun_headshot %>
</p>

<p>
  <strong>Mag size:</strong>
  <%= @gun.mag_size %>
</p>

<%= link_to 'Edit', edit_gun_path(@gun) %> |
<%= link_to 'Back', guns_path %>

app/views/items/attachment_stats.html.erb
<div class="background">
	<div class="main">

<h1><%= @attachment.atmt_name %></h1>

<p>
  <strong>Type:</strong>
  <%= @attachment.atmt_type %>
</p>

<p>
  <strong>Attaches To:</strong>
  <%= @attachment.attaches_to %>
</p>

<p>
  <strong>Color:</strong>
  <%= @attachment.color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @attachment.description %>
</p>

</div>
</div>

app/views/items/attachments.html.erb
<div class="background">
	<div class="main">

<h1>Attachments</h1>

<p><strong>Hop Ups: </strong></br>
<% @attachments.each do |atmt| %>
	<% if(atmt.atmt_type == "Hop Up") %>
		<%= link_to(atmt.atmt_name, {:controller => 'items', :action => 'attachment_stats', :id => atmt.id}) %></br>
	<% end %>
<% end %>
</p>

<p><strong>Optics: </strong></br>
<% @attachments.each do |atmt| %>
	<% if(atmt.atmt_type == "Optic") %>
		<%= link_to(atmt.atmt_name, {:controller => 'items', :action => 'attachment_stats', :id => atmt.id}) %></br>
	<% end %>
<% end %>
</p>

<p><strong>Magazine: </strong></br>
<% @attachments.each do |atmt| %>
	<% if(atmt.atmt_type == "Magazine") %>
		<%= link_to(atmt.atmt_name, {:controller => 'items', :action => 'attachment_stats', :id => atmt.id}) %></br>
	<% end %>
<% end %>
</p>

<p><strong>Barrel: </strong></br>
<% @attachments.each do |atmt| %>
	<% if(atmt.atmt_type == "Barrel") %>
		<%= link_to(atmt.atmt_name, {:controller => 'items', :action => 'attachment_stats', :id => atmt.id}) %></br>
	<% end %>
<% end %>
</p>

<p><strong>Stock: </strong></br>
<% @attachments.each do |atmt| %>
	<% if(atmt.atmt_type == "Stock") %>
		<%= link_to(atmt.atmt_name, {:controller => 'items', :action => 'attachment_stats', :id => atmt.id}) %></br>
	<% end %>
<% end %>
</p>

<%= link_to("Back", {:controller => 'items', :action => 'index'}) %>


</div>
</div>

app/views/items/consumables.html.erb
<h1>Items#consumables</h1>
<p>Find me in app/views/items/consumables.html.erb</p>

app/views/items/gun_stats.html.erb
<div class="background">
	<div class="main">

	<h1><%= @gun.gun_name %></h1>

	<p>
  	<strong>Gun type:</strong>
  	<%= @gun.gun_type %>
	</p>

	<p>
  	<strong>Ammo type:</strong>
  	<%= @gun.ammo_type %>
	</p>

	<p>
  	<strong>Gun description:</strong>
  	<%= @gun.gun_description %>
	</p>

	<p>
  	<strong>Gun damage:</strong>
  	<%= @gun.gun_body %>
	</p>

	<p>
  	<strong>Headshot damage:</strong>
  	<%= @gun.gun_headshot %>
	</p>

	<p>
  	<strong>Mag Size:</strong>
  	<%= @gun.mag_size %>
	</p>

	<% path = "/assets/guns/" + @gun.gun_name + ".PNG" %>
	<%= image_tag (path)%>

	</div>
</div>

app/views/items/guns.html.erb
<div class="background">
	<div class="main">

	<h1>Guns</h1>

	<p><strong>Pistols: </strong></br>
	<% @guns.each do |gun| %>
		<% if(gun.gun_type == "Pistol") %>
			<%= link_to(gun.gun_name, {:controller => 'items', :action => 'gun_stats', :id => gun.id}) %></br>
		<% end %>
	<% end %>
	</p>

	<p><strong>Sub Machine Guns: </strong></br>
	<% @guns.each do |gun| %>
		<% if(gun.gun_type == "Sub Machine Gun") %>
			<%= link_to(gun.gun_name, {:controller => 'items', :action => 'gun_stats', :id => gun.id}) %></br>
		<% end %>
	<% end %>	
	</p>

	<p><strong>Assault Rifles: </strong></br>
	<% @guns.each do |gun| %>
		<% if(gun.gun_type == "Assault Rifle") %>
			<%= link_to(gun.gun_name, {:controller => 'items', :action => 'gun_stats', :id => gun.id}) %></br>
		<% end %>
	<% end %>
	</p>

	<p><strong>Light Machine Guns: </strong></br>
	<% @guns.each do |gun| %>
		<% if(gun.gun_type == "Light Machine Gun") %>
			<%= link_to(gun.gun_name, {:controller => 'items', :action => 'gun_stats', :id => gun.id}) %></br>
		<% end %>
	<% end %>
	</p>

	<p><strong>Sniper Rifles: </strong></br>
	<% @guns.each do |gun| %>
		<% if(gun.gun_type == "Sniper Rifle") %>
			<%= link_to(gun.gun_name, {:controller => 'items', :action => 'gun_stats', :id => gun.id}) %></br>
		<% end %>
	<% end %>
	</p>

	<p><strong>Shotguns: </strong></br>
	<% @guns.each do |gun| %>
		<% if(gun.gun_type == "Shotgun") %>
			<%= link_to(gun.gun_name, {:controller => 'items', :action => 'gun_stats', :id => gun.id}) %></br>
		<% end %>
	<% end %>
	</p>

	<%= link_to("Back", {:controller => 'items', :action => 'index'}) %>

	</div>
</div>

app/views/items/index.html.erb


<div class="background">
	<div class="main">
		<h1>Items</h1>
		<%= link_to("Legends", {:controller => 'items', :action => 'legends'}) %>
		<%= link_to("Guns", {:controller => 'items', :action => 'guns'}) %>
		<%= link_to("Attachments", {:controller => 'items', :action => 'attachments'}) %>
		<%= link_to("Consumables", {:controller => 'items', :action => 'consumables'}) %>

		</br>
		<% if(params.has_key?(:id)) %>
		<%= "Gun ID: #{@gun_id}" %>
		<% end %>

		<%= link_to("Back", {:controller => 'welcome', :action => 'index'}) %>
		</div>
</div>

app/views/items/legend_stats.html.erb
<div class="background">
	<div class="main">

<h1><%= @legend.legend_name %></h1>

<p>
  <strong>Description:</strong>
  <%= @legend.legend_desc %>
</p>

<p>
  <strong><%= @legend.legend_passive_name %>:</strong>
  <%= @legend.legend_passive_desc %>
</p>

<p>
  <strong><%= @legend.legend_ability_name %>:</strong>
  <%= @legend.legend_ability_desc %>
</p>

<p>
  <strong><%= @legend.legend_ult_name %>:</strong>
  <%= @legend.legend_ult_desc %>
</p>

</div>
</div>

app/views/items/legends.html.erb
<div class="background">
	<div class="main">

		<% @legends.each do |leg| %>
			<%= link_to(leg.legend_name, {:controller => 'items', :action => 'legend_stats', :id => leg.id}) %></br>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApexLegends</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/legends/_form.html.erb
<%= form_with(model: legend, local: true) do |form| %>
  <% if legend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(legend.errors.count, "error") %> prohibited this legend from being saved:</h2>

      <ul>
      <% legend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :legend_name %>
    <%= form.text_field :legend_name, id: :legend_legend_name %>
  </div>

  <div class="field">
    <%= form.label :legend_desc %>
    <%= form.text_field :legend_desc, id: :legend_legend_desc %>
  </div>

  <div class="field">
    <%= form.label :legend_passive_name %>
    <%= form.text_field :legend_passive_name, id: :legend_legend_passive_name %>
  </div>

  <div class="field">
    <%= form.label :legend_passive_desc %>
    <%= form.text_field :legend_passive_desc, id: :legend_legend_passive_desc %>
  </div>

  <div class="field">
    <%= form.label :legend_ability_name %>
    <%= form.text_field :legend_ability_name, id: :legend_legend_ability_name %>
  </div>

  <div class="field">
    <%= form.label :legend_ability_desc %>
    <%= form.text_field :legend_ability_desc, id: :legend_legend_ability_desc %>
  </div>

  <div class="field">
    <%= form.label :legend_ult_name %>
    <%= form.text_field :legend_ult_name, id: :legend_legend_ult_name %>
  </div>

  <div class="field">
    <%= form.label :legend_ult_desc %>
    <%= form.text_field :legend_ult_desc, id: :legend_legend_ult_desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/legends/edit.html.erb
<h1>Editing Legend</h1>

<%= render 'form', legend: @legend %>

<%= link_to 'Show', @legend %> |
<%= link_to 'Back', legends_path %>

app/views/legends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Legends</h1>

<table>
  <thead>
    <tr>
      <th>Legend name</th>
      <th>Legend desc</th>
      <th>Legend passive name</th>
      <th>Legend passive desc</th>
      <th>Legend ability name</th>
      <th>Legend ability desc</th>
      <th>Legend ult name</th>
      <th>Legend ult desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @legends.each do |legend| %>
      <tr>
        <td><%= legend.legend_name %></td>
        <td><%= legend.legend_desc %></td>
        <td><%= legend.legend_passive_name %></td>
        <td><%= legend.legend_passive_desc %></td>
        <td><%= legend.legend_ability_name %></td>
        <td><%= legend.legend_ability_desc %></td>
        <td><%= legend.legend_ult_name %></td>
        <td><%= legend.legend_ult_desc %></td>
        <td><%= link_to 'Show', legend %></td>
        <td><%= link_to 'Edit', edit_legend_path(legend) %></td>
        <td><%= link_to 'Destroy', legend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Legend', new_legend_path %>

app/views/legends/new.html.erb
<h1>New Legend</h1>

<%= render 'form', legend: @legend %>

<%= link_to 'Back', legends_path %>

app/views/legends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Legend name:</strong>
  <%= @legend.legend_name %>
</p>

<p>
  <strong>Legend desc:</strong>
  <%= @legend.legend_desc %>
</p>

<p>
  <strong>Legend passive name:</strong>
  <%= @legend.legend_passive_name %>
</p>

<p>
  <strong>Legend passive desc:</strong>
  <%= @legend.legend_passive_desc %>
</p>

<p>
  <strong>Legend ability name:</strong>
  <%= @legend.legend_ability_name %>
</p>

<p>
  <strong>Legend ability desc:</strong>
  <%= @legend.legend_ability_desc %>
</p>

<p>
  <strong>Legend ult name:</strong>
  <%= @legend.legend_ult_name %>
</p>

<p>
  <strong>Legend ult desc:</strong>
  <%= @legend.legend_ult_desc %>
</p>

<%= link_to 'Edit', edit_legend_path(@legend) %> |
<%= link_to 'Back', legends_path %>

app/views/welcome/index.html.erb
<div class="background">
	<div class="main">

<h1>Welcome to the site!</h1>


<input type="text" name="player" id="player"/>
<input type="button" value="Search" onclick="search()"></br>
<!--%= link_to("Search", {:controller => 'profile', :action => 'index', :user => 'thegreatDORF'}) %></br-->
<%= link_to("Go To Legends/Items", {:controller => 'items', :action => 'index'}) %>

<script>
function search() {
  var srch = document.getElementById("player").value;
  var path = "/profile/index?user=" + String(srch);
  location.href = path
}
</script>

	</div>
</div>